import 'package:flutter/widgets.dart';
import 'package:keqdis/storages/improved_settings_storage.dart';

class AppLocalization extends ChangeNotifier {
  static final AppLocalization _instance = AppLocalization._internal();
  factory AppLocalization() => _instance;
  AppLocalization._internal();

  Locale _locale = const Locale('ru');
  Locale get locale => _locale;

  static const Map<String, Map<String, String>> _dict = {
    'ru': {
      'servers': 'Серверы',
      'subscriptions': 'Подписки',
      'settings': 'Настройки',
      'connected': 'Подключено',
      'connecting': 'Подключение...',
      'disconnected': 'Отключено',
      'main_settings': 'Основные настройки',
      'advanced_settings': 'Дополнительные настройки',
      'appearance': 'Внешний вид',
      'color_theme_title': 'Цветовая тема',
      'color_theme_hint': 'Выберите пресет интерфейса',
      'local_port': 'Локальный порт',
      'local_port_hint': 'Например: 2080',
      'use_custom_dns': 'Использовать свои DNS',
      'use_custom_dns_subtitle':
          'Применяется для system proxy и TUN режимов',
      'custom_dns_hint':
          'Через запятую: 1.1.1.1, 8.8.8.8 или https://dns.google/dns-query',
      'local_port_saved':
          'Локальный порт сохранён. Переподключитесь для применения.',
      'save': 'Сохранить',
      'app_behavior': 'Поведение приложения',
      'app_behavior_subtitle': 'Автозапуск, свертывание в трей и другое',
      'routing': 'Маршрутизация',
      'routing_subtitle': 'Правила для доменов, IP-адресов и блокировки',
      'ping_settings': 'Настройки пинга',
      'ping_settings_subtitle': 'Выбор типа пинга (TCP или через прокси)',
      'dark_theme': 'Тёмная тема',
      'language': 'Язык',
      'russian': 'Русский',
      'english': 'English',
      'change_language': 'Сменить язык приложения',
      'theme_hint': 'Переключить между светлой и тёмной темой',
      'autostart': 'Автозапуск при старте',
      'minimize_to_tray': 'Сворачивать в трей',
      'start_minimized': 'Запускать свёрнутым',
      'autoconnect': 'Автоподключение',
      'ping_tcp': 'TCP пинг',
      'ping_proxy': 'Пинг через прокси',
      'ping_tcp_description': 'Прямое подключение к серверу',
      'ping_proxy_description': 'Проверка через локальный прокси',
      'done': 'Готово',
      'cancel': 'Отмена',
      'exit': 'Выйти',
      'confirm_exit': 'Вы действительно хотите выйти?',
      'admin_required': 'Требуются права администратора',
      'tun_requires_admin':
          'Для TUN режима необходим перезапуск от имени администратора.',
      'restart': 'Перезапустить',
      'behavior_page_title': 'Поведение приложения',
      'behavior_autostart_subtitle': 'Запускать вместе с системой',
      'behavior_minimize_to_tray_subtitle':
          'При закрытии окна сворачивать в системный трей',
      'behavior_start_minimized_subtitle':
          'Сразу сворачиваться в трей при автозапуске',
      'behavior_autoconnect_subtitle':
          'Подключаться к последнему серверу при старте',
      'behavior_autostart_error': 'Не удалось настроить автозапуск: {error}',
      'behavior_saved': 'Настройки сохранены',
      'subscriptions_title': 'Подписки',
      'subscriptions_add': 'Добавить подписку',
      'subscriptions_name': 'Название',
      'subscriptions_name_hint': 'Например: Моя подписка',
      'subscriptions_url': 'URL подписки',
      'subscriptions_url_hint': 'https://example.com/sub',
      'subscriptions_auto_update_12h': 'Автообновление каждые 12ч',
      'subscriptions_cancel': 'Отмена',
      'subscriptions_add_button': 'Добавить',
      'subscriptions_fill_all_fields': 'Заполните все поля',
      'subscriptions_added_loading': 'Подписка добавлена, загрузка...',
      'subscriptions_loaded_servers': 'Загружено {count} серверов',
      'subscriptions_error': 'Ошибка: {error}',
      'subscriptions_load_error': 'Ошибка загрузки: {error}',
      'subscriptions_update_all': 'Обновить все',
      'subscriptions_empty': 'Нет подписок',
      'subscriptions_empty_hint': 'Нажмите + чтобы добавить',
      'subscriptions_delete_title': 'Удалить подписку?',
      'subscriptions_delete_warning': 'Серверы из этой подписки будут удалены.',
      'subscriptions_delete': 'Удалить',
      'subscriptions_deleted': 'Подписка удалена',
      'subscriptions_updated_summary':
          'Обновлено {ok} подписок, {servers} серверов',
      'subscriptions_update': 'Обновить',
      'subscriptions_auto_update': 'Автообновление',
      'subscriptions_edit': 'Редактировать',
      'subscriptions_edit_title': 'Редактирование подписки',
      'subscriptions_expand': 'Развернуть',
      'subscriptions_collapse': 'Свернуть',
      'subscriptions_servers_count': '{count} серверов',
      'subscriptions_traffic': 'Трафик: {used} / {total}',
      'subscriptions_updated_at': 'Обновлено: {date}',
      'just_now': 'только что',
      'minutes_ago': '{minutes} мин назад',
      'hours_ago': '{hours} ч назад',
      'yesterday': 'вчера',
      'days_ago': '{days} дн назад',
      'expiry_passed': 'Срок действия истек',
      'expiry_left_days_hours': 'До окончания: {days}д {hours}ч',
      'expiry_left_hours_minutes': 'До окончания: {hours}ч {minutes}м',
      'routing_saved': 'Правила маршрутизации сохранены',
      'routing_info':
          'Добавляйте домены и IP-адреса для гибкой маршрутизации трафика',
      'routing_direct_title': 'Прямое подключение (Direct)',
      'routing_direct_subtitle': 'Домены, которые будут открываться без VPN',
      'routing_proxy_title': 'Принудительно через VPN (Proxy)',
      'routing_proxy_subtitle': 'Домены, которые всегда будут идти через VPN',
      'routing_block_title': 'Заблокированные (Block)',
      'routing_block_subtitle': 'Домены, к которым будет запрещен доступ',
      'routing_ip_title': 'IP адреса (Direct)',
      'routing_ip_subtitle': 'IP адреса или подсети для прямого подключения',
      'routing_placeholder_domain_example': 'Например: yandex.ru или ru',
      'routing_placeholder_proxy_example': 'Например: google.com',
      'routing_placeholder_block_example': 'Например: ads.example.com',
      'routing_placeholder_ip_example': 'Например: 192.168.0.0/16',
      'routing_presets': 'Пресеты',
      'routing_clear_all': 'Очистить всё',
      'routing_no_items': 'Нет элементов',
      'routing_total_items': 'Всего: {count}',
      'routing_invalid_format': 'Некорректный формат: {value}',
      'routing_enter_domain': 'Введите домен',
      'routing_preset_added': 'Пресет добавлен',
      'routing_title': 'Маршрутизация',
      'routing_help_title': 'Справка маршрутизации',
      'routing_help_direct_title': 'Прямое подключение (Direct)',
      'routing_help_direct_text': 'Домены открываются напрямую без VPN.',
      'routing_help_proxy_title': 'Принудительно через VPN (Proxy)',
      'routing_help_proxy_text':
          'Домены всегда идут через VPN, независимо от других правил.',
      'routing_help_block_title': 'Заблокированные (Block)',
      'routing_help_block_text': 'Полностью запрещённый доступ к домену.',
      'routing_help_apps_title': 'Приложения (только TUN-режим)',
      'routing_help_apps_text':
          'Выбранные приложения будут маршрутизироваться через VPN по имени процесса.',
      'routing_help_formats_title': 'Форматы записей:',
      'routing_help_formats_list':
          '• TLD: ru, com, net\n• Домен: google.com, yandex.ru\n• Поддомены: .google.com\n• IP: 192.168.1.1\n• CIDR: 192.168.0.0/16\n• Точное: full:example.com\n• Regex: regexp:.*\\\\.ads\\\\..*',
      'routing_help_hint':
          'Указывайте правило в нужном формате: для зоны — ru, для домена — google.com, для всех поддоменов — .google.com.',
      'routing_help_close': 'Понятно',
      'domains_and_ips_tab': 'Домены и IP',
      'apps_tab': 'Приложения',
      'save_routing_settings': 'Сохранить настройки',
      'apps_routing_tun_only_banner': 'Работает только в TUN-режиме',
      'apps_routing_mode_title': 'Режим маршрутизации',
      'apps_routing_mode_all_proxy': 'Всё через VPN',
      'apps_routing_mode_only_selected': 'Только выбранные',
      'apps_routing_mode_all_except_selected': 'Всё кроме выбранных',
      'apps_routing_mode_changed': 'Режим: {mode}',
      'apps_routing_all_proxy': 'Весь трафик идёт через VPN',
      'apps_routing_all_proxy_hint':
          'Выберите другой режим для настройки\nмаршрутизации по приложениям',
      'apps_tab_installed': 'Установленные',
      'apps_tab_running': 'Запущенные',
      'apps_search_hint': 'Поиск...',
      'apps_refresh': 'Обновить',
      'apps_clear_all': 'Снять все',
      'apps_loading_running': 'Получение запущенных процессов...',
      'apps_loading_installed': 'Загрузка приложений...',
      'apps_load_failed': 'Не удалось загрузить список',
      'apps_retry': 'Повторить',
      'apps_no_running': 'Нет запущенных приложений',
      'apps_not_found': 'Приложения не найдены',
      'apps_nothing_found': 'Ничего не найдено: {query}',
      'apps_not_in_current_list': 'Не найдено в текущем списке',
      'apps_settings_changed': 'Настройки изменились',
      'apps_reconnect_required': 'Для применения нужно переподключиться',
      'apps_reconnect': 'Переподключить',
      'apps_saved_count': 'Сохранено: {count} приложений',
      'apps_list_cleared': 'Список очищен',
      'background_opacity': 'Прозрачность фона',
      'background_blur': 'Размытие фона',
      'background_change': 'Изменить фон',
      'background_select': 'Выбрать фоновое изображение',
      'background_auto_colors':
          'Цвета интерфейса сохраняются из выбранного пресета',
      'add_server': 'Добавить сервер',
      'ping_all_servers': 'Пинг всех серверов',
      'no_servers': 'Нет серверов',
      'servers_not_found': 'Серверы не найдены',
      'select_server': 'Выберите сервер',
      'selected_server': 'Выбранный сервер',
      'subscription_expired': 'Подписка истекла',
      'subscription_not_found': 'Подписка не найдена',
      'subscription_updated': 'Подписка "{name}" обновлена: {count} серверов',
      'subscription_update_failed': 'Не удалось обновить подписку',
      'subscription_update_error': 'Ошибка обновления: {error}',
      'subscription_no_configs': 'Для этой подписки нет конфигураций',
      'configs_saved': 'Конфигурации сохранены: {path}',
      'configs_save_error': 'Ошибка сохранения конфигов: {error}',
      'manual_servers': 'Ручные серверы',
      'server_deleted': 'Сервер удалён',
      'subscription_refresh': 'Обновить подписку',
      'subscription_download_configs': 'Скачать конфигурации',
      'vpn_ping_unavailable': 'Недоступен',
      'vpn_ping_tooltip': 'Проверить пинг',
      'vpn_favorite_tooltip': 'Избранное',
      'vpn_delete_tooltip': 'Удалить',
      'vpn_tun_admin_required': 'TUN режим (требуются права администратора)',
      'vpn_disconnect_to_switch': 'Отключитесь для смены режима',
      'search_servers_hint': 'Поиск серверов...',
      'add_servers_title': 'Добавить серверы',
      'add_servers_hint':
          'Вставьте один или несколько конфигов\n(каждый с новой строки)',
      'paste_from_clipboard': 'Вставить из буфера',
      'dialog_add': 'Добавить',
      'processing_image': 'Обработка изображения...',
      'background_set_optimized':
          'Фон установлен (оптимизировано для производительности)',
      'background_error': 'Ошибка: {error}',
      'background_removed': 'Фон удален',
      'pick_color_title': 'Выберите цвет',
      'theme_settings_title': 'Настройки темы',
      'background_image_title': 'Фоновое изображение',
      'background_set': 'Фон установлен',
      'background_delete': 'Удалить фон',
      'background_optimized_hint':
          'Изображение оптимизировано до Full HD для лучшей производительности',
      'background_transparency': 'Прозрачность',
      'background_blur_label': 'Размытие',
      'background_pick_image': 'Выбрать изображение',
      'background_any_image_hint':
          'Любое изображение будет автоматически оптимизировано до Full HD (1920x1080) для лучшей производительности',
      'color_scheme': 'Цветовая схема',
      'primary_color': 'Основной цвет',
      'secondary_color': 'Вторичный цвет',
      'card_background_color': 'Цвет фона карточек',
      'debug_mode': 'Режим отладки',
      'debug_mode_subtitle': 'Показывать инструменты диагностики в настройках',
      'share_device_hwid': 'Передавать HWID в подписках',
      'share_device_hwid_subtitle':
          'Некоторые провайдеры требуют HWID для выдачи рабочих конфигов',
      'open_debug_logs': 'Открыть логи приложения',
      'open_debug_logs_subtitle':
          'Просмотр системных и диагностических сообщений',
      'debug_logs_title': 'Логи приложения',
      'debug_logs_empty': 'Логи пока отсутствуют',
      'clear_logs': 'Очистить логи',
      'copy_logs': 'Копировать логи',
      'logs_copied': 'Логи скопированы в буфер обмена',
    },
    'en': {
      'servers': 'Servers',
      'subscriptions': 'Subscriptions',
      'settings': 'Settings',
      'connected': 'Connected',
      'connecting': 'Connecting...',
      'disconnected': 'Disconnected',
      'main_settings': 'Main settings',
      'advanced_settings': 'Advanced settings',
      'appearance': 'Appearance',
      'color_theme_title': 'Color theme',
      'color_theme_hint': 'Choose an interface preset',
      'local_port': 'Local port',
      'local_port_hint': 'For example: 2080',
      'use_custom_dns': 'Use custom DNS',
      'use_custom_dns_subtitle':
          'Applied for both system proxy and TUN modes',
      'custom_dns_hint':
          'Comma-separated: 1.1.1.1, 8.8.8.8 or https://dns.google/dns-query',
      'local_port_saved': 'Local port saved. Reconnect to apply.',
      'save': 'Save',
      'app_behavior': 'App behavior',
      'app_behavior_subtitle': 'Autostart, minimize to tray and more',
      'routing': 'Routing',
      'routing_subtitle': 'Rules for domains, IPs and blocking',
      'ping_settings': 'Ping settings',
      'ping_settings_subtitle': 'Choose ping type (TCP or via proxy)',
      'dark_theme': 'Dark theme',
      'language': 'Language',
      'russian': 'Russian',
      'english': 'English',
      'change_language': 'Change app language',
      'theme_hint': 'Switch between light and dark theme',
      'autostart': 'Autostart',
      'minimize_to_tray': 'Minimize to tray',
      'start_minimized': 'Start minimized',
      'autoconnect': 'Auto-connect',
      'ping_tcp': 'TCP ping',
      'ping_proxy': 'Proxy ping',
      'ping_tcp_description': 'Direct connection to server',
      'ping_proxy_description': 'Check via local proxy',
      'done': 'Done',
      'cancel': 'Cancel',
      'exit': 'Exit',
      'confirm_exit': 'Do you really want to exit?',
      'admin_required': 'Administrator rights required',
      'tun_requires_admin':
          'TUN mode requires restarting app as Administrator.',
      'restart': 'Restart',
      'behavior_page_title': 'App behavior',
      'behavior_autostart_subtitle': 'Start together with the system',
      'behavior_minimize_to_tray_subtitle':
          'Minimize to system tray when closing window',
      'behavior_start_minimized_subtitle':
          'Immediately minimize to tray on autostart',
      'behavior_autoconnect_subtitle': 'Connect to last server on start',
      'behavior_autostart_error': 'Failed to configure autostart: {error}',
      'behavior_saved': 'Settings saved',
      'subscriptions_title': 'Subscriptions',
      'subscriptions_add': 'Add subscription',
      'subscriptions_name': 'Name',
      'subscriptions_name_hint': 'For example: My subscription',
      'subscriptions_url': 'Subscription URL',
      'subscriptions_url_hint': 'https://example.com/sub',
      'subscriptions_auto_update_12h': 'Auto-update every 12h',
      'subscriptions_cancel': 'Cancel',
      'subscriptions_add_button': 'Add',
      'subscriptions_fill_all_fields': 'Fill in all fields',
      'subscriptions_added_loading': 'Subscription added, loading...',
      'subscriptions_loaded_servers': 'Loaded {count} servers',
      'subscriptions_error': 'Error: {error}',
      'subscriptions_load_error': 'Load error: {error}',
      'subscriptions_update_all': 'Update all',
      'subscriptions_empty': 'No subscriptions',
      'subscriptions_empty_hint': 'Press + to add',
      'subscriptions_delete_title': 'Delete subscription?',
      'subscriptions_delete_warning':
          'Servers from this subscription will be removed.',
      'subscriptions_delete': 'Delete',
      'subscriptions_deleted': 'Subscription deleted',
      'subscriptions_updated_summary':
          'Updated {ok} subscriptions, {servers} servers',
      'subscriptions_update': 'Update',
      'subscriptions_auto_update': 'Auto-update',
      'subscriptions_edit': 'Edit',
      'subscriptions_edit_title': 'Edit subscription',
      'subscriptions_expand': 'Expand',
      'subscriptions_collapse': 'Collapse',
      'subscriptions_servers_count': '{count} servers',
      'subscriptions_traffic': 'Traffic: {used} / {total}',
      'subscriptions_updated_at': 'Updated: {date}',
      'just_now': 'just now',
      'minutes_ago': '{minutes} min ago',
      'hours_ago': '{hours} h ago',
      'yesterday': 'yesterday',
      'days_ago': '{days} d ago',
      'expiry_passed': 'Expired',
      'expiry_left_days_hours': 'Left: {days}d {hours}h',
      'expiry_left_hours_minutes': 'Left: {hours}h {minutes}m',
      'routing_saved': 'Routing rules saved',
      'routing_info':
          'Add domains and IP-addresses for flexible traffic routing',
      'routing_direct_title': 'Direct connection (Direct)',
      'routing_direct_subtitle': 'Domains that will open without VPN',
      'routing_proxy_title': 'Force via VPN (Proxy)',
      'routing_proxy_subtitle': 'Domains that always go via VPN',
      'routing_block_title': 'Blocked (Block)',
      'routing_block_subtitle': 'Domains that will be blocked',
      'routing_ip_title': 'IP addresses (Direct)',
      'routing_ip_subtitle': 'IP addresses or subnets for direct connection',
      'routing_placeholder_domain_example': 'Example: yandex.ru or ru',
      'routing_placeholder_proxy_example': 'Example: google.com',
      'routing_placeholder_block_example': 'Example: ads.example.com',
      'routing_placeholder_ip_example': 'Example: 192.168.0.0/16',
      'routing_presets': 'Presets',
      'routing_clear_all': 'Clear all',
      'routing_no_items': 'No items',
      'routing_total_items': 'Total: {count}',
      'routing_invalid_format': 'Invalid format: {value}',
      'routing_enter_domain': 'Enter domain',
      'routing_preset_added': 'Preset added',
      'routing_title': 'Routing',
      'routing_help_title': 'Routing help',
      'routing_help_direct_title': 'Direct connection (Direct)',
      'routing_help_direct_text': 'Domains open directly without VPN.',
      'routing_help_proxy_title': 'Force via VPN (Proxy)',
      'routing_help_proxy_text':
          'Domains always go via VPN regardless of other rules.',
      'routing_help_block_title': 'Blocked (Block)',
      'routing_help_block_text': 'Completely blocked access to domain.',
      'routing_help_apps_title': 'Apps (TUN mode only)',
      'routing_help_apps_text':
          'Selected apps will be routed via VPN by process name.',
      'routing_help_formats_title': 'Formats:',
      'routing_help_formats_list':
          '• TLD: ru, com, net\n• Domain: google.com, yandex.ru\n• Subdomains: .google.com\n• IP: 192.168.1.1\n• CIDR: 192.168.0.0/16\n• Exact: full:example.com\n• Regex: regexp:.*\\\\.ads\\\\..*',
      'routing_help_hint':
          'Use the matching format for each rule: zone — ru, domain — google.com, all subdomains — .google.com.',
      'routing_help_close': 'Got it',
      'domains_and_ips_tab': 'Domains and IPs',
      'apps_tab': 'Applications',
      'save_routing_settings': 'Save settings',
      'apps_routing_tun_only_banner': 'Works only in TUN mode',
      'apps_routing_mode_title': 'Routing mode',
      'apps_routing_mode_all_proxy': 'All via VPN',
      'apps_routing_mode_only_selected': 'Only selected',
      'apps_routing_mode_all_except_selected': 'All except selected',
      'apps_routing_mode_changed': 'Mode: {mode}',
      'apps_routing_all_proxy': 'All traffic goes through VPN',
      'apps_routing_all_proxy_hint':
          'Choose another mode to configure\nper-app routing',
      'apps_tab_installed': 'Installed',
      'apps_tab_running': 'Running',
      'apps_search_hint': 'Search...',
      'apps_refresh': 'Refresh',
      'apps_clear_all': 'Clear all',
      'apps_loading_running': 'Getting running processes...',
      'apps_loading_installed': 'Loading apps...',
      'apps_load_failed': 'Failed to load list',
      'apps_retry': 'Retry',
      'apps_no_running': 'No running apps',
      'apps_not_found': 'Apps not found',
      'apps_nothing_found': 'Nothing found: {query}',
      'apps_not_in_current_list': 'Not found in current list',
      'apps_settings_changed': 'Settings changed',
      'apps_reconnect_required': 'Reconnect is required to apply',
      'apps_reconnect': 'Reconnect',
      'apps_saved_count': 'Saved: {count} apps',
      'apps_list_cleared': 'List cleared',
      'background_opacity': 'Background opacity',
      'background_blur': 'Background blur',
      'background_change': 'Change background',
      'background_select': 'Choose background image',
      'background_auto_colors':
          'Interface colors are kept from the selected preset',
      'add_server': 'Add server',
      'ping_all_servers': 'Ping all servers',
      'no_servers': 'No servers',
      'servers_not_found': 'Servers not found',
      'select_server': 'Select server',
      'selected_server': 'Selected server',
      'subscription_expired': 'Subscription expired',
      'subscription_not_found': 'Subscription not found',
      'subscription_updated': 'Subscription "{name}" updated: {count} servers',
      'subscription_update_failed': 'Failed to update subscription',
      'subscription_update_error': 'Update error: {error}',
      'subscription_no_configs': 'No configs for this subscription',
      'configs_saved': 'Configs saved: {path}',
      'configs_save_error': 'Failed to save configs: {error}',
      'manual_servers': 'Manual servers',
      'server_deleted': 'Server deleted',
      'subscription_refresh': 'Refresh subscription',
      'subscription_download_configs': 'Download configs',
      'vpn_ping_unavailable': 'Unavailable',
      'vpn_ping_tooltip': 'Check ping',
      'vpn_favorite_tooltip': 'Favorite',
      'vpn_delete_tooltip': 'Delete',
      'vpn_tun_admin_required': 'TUN mode (administrator rights required)',
      'vpn_disconnect_to_switch': 'Disconnect to change mode',
      'search_servers_hint': 'Search servers...',
      'add_servers_title': 'Add servers',
      'add_servers_hint': 'Paste one or more configs\n(each on new line)',
      'paste_from_clipboard': 'Paste from clipboard',
      'dialog_add': 'Add',
      'processing_image': 'Processing image...',
      'background_set_optimized': 'Background set (optimized for performance)',
      'background_error': 'Error: {error}',
      'background_removed': 'Background removed',
      'pick_color_title': 'Pick a color',
      'theme_settings_title': 'Theme settings',
      'background_image_title': 'Background image',
      'background_set': 'Background set',
      'background_delete': 'Delete background',
      'background_optimized_hint':
          'Image optimized to Full HD for better performance',
      'background_transparency': 'Transparency',
      'background_blur_label': 'Blur',
      'background_pick_image': 'Choose image',
      'background_any_image_hint':
          'Any image will be automatically optimized to Full HD (1920x1080) for better performance',
      'color_scheme': 'Color scheme',
      'primary_color': 'Primary color',
      'secondary_color': 'Secondary color',
      'card_background_color': 'Card background color',
      'debug_mode': 'Debug mode',
      'debug_mode_subtitle': 'Show diagnostic tools in settings',
      'share_device_hwid': 'Send HWID with subscriptions',
      'share_device_hwid_subtitle':
          'Some providers require HWID to return valid configs',
      'open_debug_logs': 'Open app logs',
      'open_debug_logs_subtitle': 'View system and diagnostic messages',
      'debug_logs_title': 'App logs',
      'debug_logs_empty': 'No logs yet',
      'clear_logs': 'Clear logs',
      'copy_logs': 'Copy logs',
      'logs_copied': 'Logs copied to clipboard',
    },
  };

  Future<void> load() async {
    final settings = await SettingsStorage.loadSettings();
    _locale = Locale(settings.appLanguage == 'en' ? 'en' : 'ru');
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    final normalized = code == 'en' ? 'en' : 'ru';
    if (_locale.languageCode == normalized) return;

    final cur = await SettingsStorage.loadSettings();
    await SettingsStorage.saveSettings(
      AppSettings(
        localPort: cur.localPort,
        useCustomDns: cur.useCustomDns,
        customDnsServers: cur.customDnsServers,
        directDomains: cur.directDomains,
        blockedDomains: cur.blockedDomains,
        directIps: cur.directIps,
        proxyDomains: cur.proxyDomains,
        autoStart: cur.autoStart,
        minimizeToTray: cur.minimizeToTray,
        startMinimized: cur.startMinimized,
        pingType: cur.pingType,
        autoConnectLastServer: cur.autoConnectLastServer,
        lastVpnMode: cur.lastVpnMode,
        appLanguage: normalized,
        debugMode: cur.debugMode,
        shareDeviceHwid: cur.shareDeviceHwid,
        deviceHwid: cur.deviceHwid,
      ),
    );

    _locale = Locale(normalized);
    notifyListeners();
  }

  String t(String key) {
    return _dict[_locale.languageCode]?[key] ?? _dict['ru']?[key] ?? key;
  }
}

extension AppLocalizationX on BuildContext {
  String tr(String key) => AppLocalization().t(key);
}
